### ISSUE TITLE
Can't run Mig33 v4

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Perundurai-Products/microemu#89]
```
I tried to run Mig33v4 (any version), but microemulator just hang there in 
loading splash screen, no more activities.
Login screen never show up.
here what I take from the terminal logs.
openJad [file:///home/ghie/./me/apps/mig33v4.jad]
      org.microemu.app.Common.openMIDletUrl(Common.java:371)
openJar [mig33v4.jar]
      org.microemu.app.Common.loadJar(Common.java:554)
openJar url [file:/home/ghie/./me/apps/mig33v4.jar]
      org.microemu.app.Common.loadJar(Common.java:572)
MIDletThread throws
      org.microemu.app.util.MIDletThread.run(MIDletThread.java:101)
java.lang.NullPointerException
   at javax.microedition.lcdui.Displayable.removeCommand(Displayable.java:84)
   at ay.g(Unknown Source)
   at ay.run(Unknown Source)
   at java.lang.Thread.run(Thread.java:745)
   at org.microemu.app.util.MIDletThread.run(MIDletThread.java:99)

I'm using Microemulator v2.0.4.62, running on Ubuntu Lucid Lynx 10.04.1.
is there something I miss?
Thanks.
```

Original issue reported on code.google.com by `Ghie...@gmail.com` on 26 Dec 2010 at 2:04

**Comment by GoogleCodeExporter** [comment]
```
Does it work with the MicroEmulator 3 snapshot version? It is available for 
download from http://snapshot.microemu.org/microemulator/download/
```

Original comment by `bar...@gmail.com` on 27 Dec 2010 at 10:36

**Comment by GoogleCodeExporter** [comment]
```
I tried MicroEmulator 3 Snapshot as you point me there, and MicroEmulator able 
to pass that loading splash screen, and the Login Form shows up.
But, whenever I tried to login to mig33, the application (Mig33v4.Jar) crash, 
no reaction from there, and MicroEmulator just Hang.
MicroEmulator works fine with older version of Mig33 (V3.02 or v3.08), but no 
luck in v4 and newer.

this what I note from the Terminal window when that error happen:

Mig33v4.3 (latest):
openJar [mig33v4.jar]
      org.microemu.app.Common.loadJar(Common.java:559)
openJar url [file:/home/ghie/./me/apps/mig33v4.jar]
      org.microemu.app.Common.loadJar(Common.java:577)
Exception in thread "event-thread" java.lang.NoClassDefFoundError: 
javax/microedition/media/Manager
   at ay.F(Unknown Source)
   at am.a(Unknown Source)
   at ay.h(Unknown Source)
   at ay.commandAction(Unknown Source)
   at ay.keyPressed(Unknown Source)
   at javax.microedition.lcdui.Display$KeyEvent.run(Display.java:153)
   at org.microemu.device.ui.EventDispatcher.post(EventDispatcher.java:164)
   at org.microemu.device.ui.EventDispatcher.run(EventDispatcher.java:99)
   at java.lang.Thread.run(Thread.java:745)
Caused by: 
org.microemu.app.classloader.MIDletClassLoader$LoadClassByParentException: 
javax.microedition.media.Manager
   at org.microemu.app.classloader.MIDletClassLoader.findClass(MIDletClassLoader.java:342)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:341)
   at org.microemu.app.classloader.MIDletClassLoader.loadClass(MIDletClassLoader.java:213)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:293)
   at ay.F(Unknown Source)
   ...8 more



Mig33v4.2:

OpenJar [file:///home/ghie/Downloads/mig33v4.jar]
      org.microemu.app.Common.loadJar(Common.java:559)
destroyMIDletContext
      org.microemu.app.Common.destroyMIDletContext(Common.java:190)
wait thread [3] end
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:146)
MIDlet timer created from [ay.I] still running
      org.microemu.app.util.MIDletTimer.terminateTimers(MIDletTimer.java:253)
openJar [file:///home/ghie/Downloads/mig33v4.jar]
      org.microemu.app.Common.loadJar(Common.java:559)
MIDlet thread [3] still running
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:155)
this thread [3] was created from ay.<init>(Unknown Source)
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:157)
wait thread [0] end
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:146)
MIDlet thread [0] still running
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:155)
this thread [0] was created from g.<init>(Unknown Source)
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:157)
wait thread [7] end
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:146)
MIDlet thread [7] still running
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:155)
this thread [7] was created from am.<init>(Unknown Source)
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:157)
wait thread [1] end
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:146)
MIDlet thread [1] still running
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:155)
this thread [1] was created from 
org.microemu.app.util.MIDletTimer.<init>(MIDletTimer.java:70)
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:157)
wait thread [5] end
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:146)
MIDlet thread [5] still running
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:155)
this thread [5] was created from ag.<init>(Unknown Source)
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:157)
wait thread [4] end
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:146)
MIDlet thread [4] still running
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:155)
this thread [4] was created from s.<init>(Unknown Source)
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:157)
wait thread [6] end
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:146)
MIDlet thread [6] still running
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:155)
this thread [6] was created from w.<init>(Unknown Source)
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:157)
wait thread [8] end
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:146)
MIDlet thread [8] still running
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:155)
this thread [8] was created from ba.b(Unknown Source)
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:157)
all 9 thread(s) finished
      org.microemu.app.util.MIDletThread.terminateThreads(MIDletThread.java:166)
Exception in thread "event-thread" java.lang.NoClassDefFoundError: 
javax/microedition/media/Manager
   at com.projectgoth.Roshan.h.u(Unknown Source)
   at com.projectgoth.Roshan.e.a(Unknown Source)
   at com.projectgoth.Roshan.h.g(Unknown Source)
   at com.projectgoth.Roshan.h.commandAction(Unknown Source)
   at com.projectgoth.Roshan.h.keyPressed(Unknown Source)
   at javax.microedition.lcdui.Display$KeyEvent.run(Display.java:153)
   at org.microemu.device.ui.EventDispatcher.post(EventDispatcher.java:164)
   at org.microemu.device.ui.EventDispatcher.run(EventDispatcher.java:99)
   at java.lang.Thread.run(Thread.java:745)
Caused by: 
org.microemu.app.classloader.MIDletClassLoader$LoadClassByParentException: 
javax.microedition.media.Manager
   at org.microemu.app.classloader.MIDletClassLoader.findClass(MIDletClassLoader.java:342)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:341)
   at org.microemu.app.classloader.MIDletClassLoader.loadClass(MIDletClassLoader.java:213)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:293)
   at com.projectgoth.Roshan.h.u(Unknown Source)
   ...8 more


please tell me, what went wrong? is it my system?

Thank you.
```

Original comment by `Ghie...@gmail.com` on 27 Dec 2010 at 12:48

**Comment by GoogleCodeExporter** [comment]
```
You should include the lib/microemu-jsr-135.jar to the classpath
```

Original comment by `bar...@gmail.com` on 27 Dec 2010 at 1:07

**Comment by GoogleCodeExporter** [comment]
```
how to do that?
I'm sorry, I'm only a user.
please tell me how to do that.
thank you.
```

Original comment by `Ghie...@gmail.com` on 27 Dec 2010 at 2:12

**Comment by GoogleCodeExporter** [comment]
```
java -cp microemulator.jar;lib/microemu-jsr-135.jar;[your midlet jar] 
org.microemu.app.Main {your midlet class}
```

Original comment by `bar...@gmail.com` on 27 Dec 2010 at 2:24

**Comment by GoogleCodeExporter** [comment]
```
I tried many ways to do what you say, but no luck.
is this "Midlet Class" thing supposed to be there, or it is generated from the 
process in that command line?
If it have to be there, I don't know where to find this Class, because mig33 
don't share such kind of file, only Jar and Jad files.
or maybe I did that command in the wrong way.
I did this:

java -cp 
microemulator.jar;lib/microemu-jsr-135.jar;/home/ghie/Downloads/mig33v4.jar 
org.microemu.app.Main {mig33v4.class}

result: 
Usage: java [-options] class [arg1 arg2 ...]
bla bla bla
bash: lib/microemu-jsr-135.jar: No such file or directory
bash: /home/ghie/Downloads/mig33v4.jar: Permission denied

And this:

java -cp 
/home/ghie/me3/microemulator.jar;/home/ghie/me3/lib/microemu-jsr-135.jar; 
/home/ghie/Downloads/mig33v4.jar org.microemu.app.Main 
{/home/ghie/Downloads/mig33v4.class}

result:

bla bla bla
bash: /home/ghie/me3/lib/microemu-jsr-135.jar: Permission denied
bash: /home/ghie/Downloads/mig33v4.jar: Permission denied

even this:

sudo java -cp 
/home/ghie/me3/microemulator.jar;/home/ghie/me3/lib/microemu-jsr-135.jar; 
/home/ghie/Downloads/mig33v4.jar org.microemu.app.Main 
/home/ghie/Downloads/mig33v4.class

and the result still the same, "Permission denied"

I know I made mistakes there, but since I'm a noob in ubuntu and java thing, I 
hope you'll understand my problem.

please give me a clear, copyable sample to paste into my terminal, and I'll be 
appreciate it.

thanks a lot.
```

Original comment by `Ghie...@gmail.com` on 27 Dec 2010 at 3:02

**Comment by GoogleCodeExporter** [comment]
```
Unix has different path separator, here is a corrected command line:
java -cp 
/home/ghie/me3/microemulator.jar:/home/ghie/me3/lib/microemu-jsr-135.jar:/home/g
hie/Downloads/mig33v4.jar org.microemu.app.Main {midlet class name}

where {midlet class name} is the name of you MIDlet class, you can find it in 
jad file
```

Original comment by `bar...@gmail.com` on 27 Dec 2010 at 3:07

**Comment by GoogleCodeExporter** [comment]
```
OK, thanks for you quick answer.
I open the Jad file, but there is no Midlet Class name there.
here is the content of jad file:

MIDlet-Version: 4.20
MIDlet-Vendor: Project Goth, Inc.
MIDlet-Jar-URL: mig33v4.jar
MIDlet-Install-Notify: http://www.mig33.com/midlet/member/c_info.php?awtrack=wap
MicroEdition-Configuration: CLDC-1.0
MIDlet-1: mig33v42,MiG33.png,com.projectgoth.Roshan.Main
MicroEdition-Profile: MIDP-2.0
MIDlet-Name: mig33v42
MIDlet-Jar-Size: 157433

which one is that Class name?

Thank you.
```

Original comment by `Ghie...@gmail.com` on 27 Dec 2010 at 3:14

**Comment by GoogleCodeExporter** [comment]
```
This is the midlet class name: com.projectgoth.Roshan.Main
```

Original comment by `bar...@gmail.com` on 27 Dec 2010 at 3:21

**Comment by GoogleCodeExporter** [comment]
```
the problem still there.
I did this:
java -cp 
/home/ghie/me3/microemulator.jar:/home/ghie/me3/lib/microemu-jsr-135.jar:/home/g
hie/Downloads/mig33v4.jar org.microemu.app.Main com.projectgoth.Roshan.Main

and I got this:

arguments [[com.projectgoth.Roshan.Main]]
      org.microemu.app.Main.main(Main.java:1050)
You are connecting to URL:74.217.68.3:9119
      com.projectgoth.Roshan.b.a(null:-1)
Exception in thread "event-thread" java.lang.NullPointerException
   at com.projectgoth.Roshan.e.a(Unknown Source)
   at com.projectgoth.Roshan.h.g(Unknown Source)
   at com.projectgoth.Roshan.h.commandAction(Unknown Source)
   at com.projectgoth.Roshan.h.keyPressed(Unknown Source)
   at javax.microedition.lcdui.Display$KeyEvent.run(Display.java:153)
   at org.microemu.device.ui.EventDispatcher.post(EventDispatcher.java:164)
   at org.microemu.device.ui.EventDispatcher.run(EventDispatcher.java:99)
   at java.lang.Thread.run(Thread.java:745)

and MicroEmulator just Hang there, in the login form.
is there something I did in a wrong way?

thank you.
```

Original comment by `Ghie...@gmail.com` on 27 Dec 2010 at 3:31

**Comment by GoogleCodeExporter** [comment]
```
Without MIDlet source code it is hard to tell anything abou that error.
```

Original comment by `bar...@gmail.com` on 27 Dec 2010 at 3:33

**Comment by GoogleCodeExporter** [comment]
```
I think it's impossible to get the source code, because mig33 is a closed 
project.
so, in sort, I can't run mig33v4 with MicroEmulator, can I?
please let me know if there is a way to deal with this issue.
Thanks for your time, I hope you can fix that problem.
```

Original comment by `Ghie...@gmail.com` on 27 Dec 2010 at 3:44
